### ISSUE TITLE
Error during the importation

### ISSUE THREAD

**Issue by djulien19** [adhoc-dev/odoo-addons#105]
Thanks for your help, I used the import module in Odoo.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/versions/odoo-odoo-community/8.0.20150625.174440/parts/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/versions/odoo-odoo-community/8.0.20150625.174440/parts/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/versions/odoo-odoo-community/8.0.20150625.174440/parts/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/versions/odoo-odoo-community/8.0.20150625.174440/parts/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/versions/odoo-odoo-community/8.0.20150625.174440/parts/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/versions/odoo-odoo-community/8.0.20150625.174440/parts/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/versions/odoo-odoo-community/8.0.20150625.174440/parts/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/production/files/parts/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/production/files/parts/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/versions/odoo-odoo-community/8.0.20150625.174440/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/production/files/parts/odoo/addons/base_import_module/models/base_import_module.py", line 29, in import_module
    res = module_obj.import_zipfile(cr, uid, fp, force=data.force, context=context)
  File "/opt/versions/odoo-odoo-community/8.0.20150625.174440/parts/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/production/files/parts/odoo/addons/base_import_module/models/ir_module.py", line 104, in import_zipfile
    errors[mod_name] = str(e)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 158: ordinal not in range(128)

**Comment by jjscarafia** [comment]
Sorry, I don't understand the error, te 'base_import_module' is the native odoo one. 
Please, follow this guid to report a bug
https://github.com/ingadhoc/odoo-argentina/wiki/Reportando-Incidencias
Thanks!
