### ISSUE TITLE
ProgrammingError: can't adapt type 'account.tax' in product_pack

### ISSUE THREAD

**Issue by mgth** [adhoc-dev/odoo-addons#113]
I got this trying to save an order : 
Traceback (most recent call last):
  File "D:\Odoo 8.0-20150603\server.\openerp\http.py", line 536, in _handle_exception
  File "D:\Odoo 8.0-20150603\server.\openerp\http.py", line 573, in dispatch
  File "D:\Odoo 8.0-20150603\server.\openerp\http.py", line 309, in _call_function
  File "D:\Odoo 8.0-20150603\server.\openerp\service\model.py", line 113, in wrapper
  File "D:\Odoo 8.0-20150603\server.\openerp\http.py", line 306, in checked_call
  File "D:\Odoo 8.0-20150603\server.\openerp\http.py", line 802, in __call__
  File "D:\Odoo 8.0-20150603\server.\openerp\http.py", line 402, in response_wrap
  File "D:\Odoo 8.0-20150603\server\openerp\addons\web\controllers\main.py", line 937, in call_kw
  File "D:\Odoo 8.0-20150603\server\openerp\addons\web\controllers\main.py", line 929, in _call_kw
  File "D:\Odoo 8.0-20150603\server.\openerp\api.py", line 241, in wrapper
  File "C:\Users\Administrateur\AppData\Local\OpenERP S.A.\Odoo\addons\8.0\product_pack\sale.py", line 126, in create
  File "D:\Odoo 8.0-20150603\server.\openerp\api.py", line 241, in wrapper
  File "C:\Users\Administrateur\AppData\Local\OpenERP S.A.\Odoo\addons\8.0\product_pack\sale.py", line 284, in expand_packs
  File "D:\Odoo 8.0-20150603\server.\openerp\api.py", line 241, in wrapper
  File "D:\Odoo 8.0-20150603\server\openerp\addons\sale\sale.py", line 1059, in create
  File "D:\Odoo 8.0-20150603\server.\openerp\api.py", line 241, in wrapper
  File "D:\Odoo 8.0-20150603\server.\openerp\api.py", line 336, in old_api
  File "D:\Odoo 8.0-20150603\server.\openerp\models.py", line 4074, in create
  File "D:\Odoo 8.0-20150603\server.\openerp\api.py", line 239, in wrapper
  File "D:\Odoo 8.0-20150603\server.\openerp\api.py", line 462, in new_api
  File "D:\Odoo 8.0-20150603\server.\openerp\models.py", line 4259, in _create
  File "D:\Odoo 8.0-20150603\server.\openerp\osv\fields.py", line 1053, in set
  File "D:\Odoo 8.0-20150603\server.\openerp\sql_db.py", line 158, in wrapper
  File "D:\Odoo 8.0-20150603\server.\openerp\sql_db.py", line 234, in execute
ProgrammingError: can't adapt type 'account.tax'

**Comment by jjscarafia** [comment]
Solved on this issue
https://github.com/adhoc-dev/odoo-addons/tree/8.0.x.imp_pack
Please test and give feedback. 
We have make several imp to product pack

**Comment by jjscarafia** [comment]
T

**Comment by lammh** [comment]
Me too i have this error, please a solution

**Comment by jjscarafia** [comment]
Sorry, this has been solved on branch 8.0.x, can you test it please?
We are going to merge 8.0.x to 8.0 in about two weeks. 
Thanks!

**Comment by lammh** [comment]
thanks for your answer ! where I can find the proper release.
and  what I do, I'm use Odoo 8

**Comment by lammh** [comment]
your link 
https://github.com/adhoc-dev/odoo-addons/tree/8.0.x.imp_pack
not working

**Comment by jjscarafia** [comment]
Sorry, you can find ir here now
https://github.com/ingadhoc/odoo-addons/tree/8.0.x?files=1
Soon in branch 8.0.x

**Comment by lammh** [comment]
![image](https://cloud.githubusercontent.com/assets/7395544/9995035/f8a4d08c-6077-11e5-80f0-8a9d07a6dc31.png)
Sorry, but no change :( thanks

**Comment by jjscarafia** [comment]
I can not replicate the error, now, pelase, check that you are working with the 8.0.x version or upload all te setps to reproduce the bug. (for this please start with a fresh database with demo data and specify how to reproduce). 
Thanks!

**Comment by lammh** [comment]
I downloaded  new version of Odoo 8, then I created a new database. but still the same problem for me

**Comment by jjscarafia** [comment]
Sorry, without stpes or more information I can not reproduce the bug.
Please be sure you are using 8.0.x branch.

**Comment by lammh** [comment]
Thank you for your patient!
I all over again and this time it works

**Comment by jjscarafia** [comment]
Great news! Soon will merge this changes to branch 8.0

**Comment by lammh** [comment]
hello, I left the job 15 days ago today I returned, I conclude that the module does not display an error if the product type is a service else the tax is not compatible

**Comment by jjscarafia** [comment]
I still can not replicate the issue. I've try with service, consumable, etc. Please If you still found the error, report as explain here https://github.com/ingadhoc/odoo-argentina/wiki/Reporting-Issues

**Comment by pgu42** [comment]
**Can not validate a Repair Order when 'To Bill' is checked**

Impacted versions:
- 9.0

Steps to reproduce:
1. Install "Repair" module
2. Create a Repair order and select a customer
3. On 'Operation' tab select 'add' on 'Operation Type', select a product and check 'To bill'
4. validate the Repair order

Current behavior: Odoo Server Error (ProgrammingError: can't adapt type 'account.tax')

Traceback (most recent call last):
  File "/openerp/openerp-server/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/openerp/openerp-server/openerp/http.py", line 636, in dispatch
    result = self._call_function(*_self.params)
  File "/openerp/openerp-server/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/openerp/openerp-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/http.py", line 308, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/openerp/openerp-server/openerp/http.py", line 887, in __call__
    return self.method(_args, *_kw)
  File "/openerp/openerp-server/openerp/http.py", line 465, in response_wrap
    response = f(_args, *_kw)
  File "/openerp/openerp-server/addons/web/controllers/main.py", line 971, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/openerp/openerp-server/addons/web/controllers/main.py", line 963, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/api.py", line 327, in old_api
    result = method(recs, _args, *_kwargs)
  File "/openerp/openerp-server/addons/mail/models/mail_thread.py", line 230, in create
    thread = super(MailThread, self).create(values)
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 4125, in create
    record = self.browse(self._create(old_vals))
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 4331, in _create
    cr, user, ids, fields2, context)
  File "/openerp/openerp-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 4469, in _store_set_values
    result = column.get(cr, self, ids, f, SUPERUSER_ID, context=context)
  File "/openerp/openerp-server/openerp/osv/fields.py", line 1489, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/openerp/openerp-server/addons/mrp_repair/mrp_repair.py", line 55, in _amount_tax
    tax_calculate = tax_obj.compute_all(cr, uid, line.tax_id, line.price_unit, cur, line.product_uom_qty, line.product_id.id, repair.partner_id.id)
  File "/openerp/openerp-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/addons/account/models/account.py", line 676, in compute_all
    return recs.compute_all(price_unit, currency, quantity, product, partner)
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/addons/account/models/account.py", line 612, in compute_all
    company_id = self[0].company_id
  File "/openerp/openerp-server/openerp/fields.py", line 807, in __get__
    self.determine_value(record)
  File "/openerp/openerp-server/openerp/fields.py", line 905, in determine_value
    record._prefetch_field(self)
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 3273, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 3203, in read
    self._read_from_database(stored, inherited)
  File "/openerp/openerp-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/models.py", line 3341, in _read_from_database
    cr.execute(query_str, params)
  File "/openerp/openerp-server/openerp/sql_db.py", line 139, in wrapper
    return f(self, _args, *_kwargs)
  File "/openerp/openerp-server/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/extensions.py", line 129, in getquoted
    pobjs = [adapt(o) for o in self._seq]
ProgrammingError: can't adapt type 'account.tax'

Expected behavior:
- Repair order validated
