### ISSUE TITLE
[V8] account_check InternalError: current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by ccarly** [adhoc-dev/odoo-addons#16]
Al crear un pago (Pago proveedores como anticipo o sea contra ninguna obligacion) y generear el cheque correspondiente, no valida el rango de cheques generando este error.

Analizando el codigo del error, no pasa en ningún momento por el modulo, pero si le asigno No. de cheque, no emite el error.

Odoo Server Error
Traceback (most recent call last):
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/home/openerp/bin/8.0/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/openerp/bin/8.0/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/openerp/bin/8.0/addons/account_check_writing/account_voucher.py", line 100, in write
    return super(account_voucher, self).write(cr, uid, ids, vals, context=context)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/openerp/bin/8.0/addons/mail/mail_thread.py", line 427, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/models.py", line 3731, in write
    self._write(old_vals)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/models.py", line 3874, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/data/home/openerp/bin/8.0/openerp/osv/fields.py", line 747, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/openerp/bin/8.0/addons/base_action_rule/base_action_rule.py", line 177, in create
    new_id = create.origin(self, cr, uid, vals, context=context, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, *_kwargs)
  File "/home/openerp/bin/8.0/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/models.py", line 4030, in create
    record = self.browse(self._create(old_vals))
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/models.py", line 4221, in _create
    recs._validate_fields(vals)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/models.py", line 1258, in _validate_fields
    res_msg = trans._get_source(self._name, 'constraint', self.env.lang, msg)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/api.py", line 441, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "<string>", line 2, in _get_source
  File "/data/home/openerp/bin/8.0/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/addons/base/ir/ir_translation.py", line 354, in _get_source
    cr.execute(query, params)
  File "/data/home/openerp/bin/8.0/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/data/home/openerp/bin/8.0/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block

**Comment by ccarly** [comment]
Solucionado con un --update=all
