### ISSUE TITLE
V9.0 Forum in zh-CN language Internal Server Error

### ISSUE THREAD

**Issue by yesonlee** [adhoc-dev/odoo-addons#240]
2015-11-30 10:30:00,482 944 INFO bode werkzeug: 127.0.0.1 - - [30/Nov/2015 10:30:00] "GET /zh_CN/forum/1/question/3 HTTP/1.0" 500 -
2015-11-30 10:30:00,490 944 ERROR bode werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1417, in **call**
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1391, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in **call**
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1581, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website_sale/models/ir_http.py", line 12, in _dispatch
    return super(IrHttp, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 162, in _dispatch
    return self.reroute('/'.join(path) or '/')
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 209, in reroute
    return self._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website_sale/models/ir_http.py", line 12, in _dispatch
    return super(IrHttp, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/utm/models/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 190, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web_editor/models/ir_http.py", line 16, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 176, in _dispatch
    return self._handle_exception(e)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 279, in _handle_exception
    context=request.context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_ui_view.py", line 85, in _views_get
    result += self._views_get(cr, uid, called_view, options=options, bundles=bundles, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_ui_view.py", line 75, in _views_get
    node = etree.fromstring(view.arch)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68106)

  File "parser.pxi", line 1785, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102455)

  File "parser.pxi", line 1666, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101214)

  File "parser.pxi", line 1035, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:96124)

  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)

  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)

  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)

XMLSyntaxError: StartTag: invalid element name, line 5, column 10
2015-11-30 10:30:43,346 944 INFO bode werkzeug: 127.0.0.1 - - [30/Nov/2015 10:30:43] "GET /en_US/forum/help-1/badge/popular-question-5 HTTP/1.0" 302 -
2015-11-30 10:30:43,621 944 INFO bode werkzeug: 127.0.0.1 - - [30/Nov/2015 10:30:43] "GET /forum/help-1/badge/popular-question-5 HTTP/1.0" 200 -

**Comment by jjscarafia** [comment]
I've deleted v9 brach as modues are not yet migrated. We will do that in 1 or 2 months
