### ISSUE TITLE
account_create_journal - Elemento DIV no encontrado

### ISSUE THREAD

**Issue by dolcey** [adhoc-dev/odoo-addons#265]
Hi there..

I tried to install the module on a clean database (odoo actual) and get the following error:

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 986, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 762, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1065, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 255, in create
    context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4093, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4284, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
El(los) campo(s) `arch` fallaron contra la restricci\xf3n: Invalid view definition

Detalles de error:
El elemento '<div name="module_account_create_journal">' no puede ser localizado en la vista padre

Error de contexto:
Vista `adhoc.base.config.settings`
[view_id: 1170, xml_id: n/a, model: adhoc.base.config.settings, parent_id: 1143]" while parsing /opt/odoo/.local/share/Odoo/addons/8.0/account_create_journal/res_config_view.xml:6, near
<record id="view_adhoc_base_configuration" model="ir.ui.view">
            <field name="name">adhoc.base.config.settings</field>
            <field name="model">adhoc.base.config.settings</field>
            <field name="inherit_id" ref="adhoc_base_setup.view_adhoc_base_configuration"/>
            <field name="arch" type="xml">
                <div name="module_account_create_journal" position="after">
                    <div attrs="{'invisible':[('module_account_create_journal','!=',True)]}">
                        <button type="action" name="%(view_journal_config_action)d" string="Configure Payment Journals." icon="gtk-execute" class="oe_link"/>
                    </div>  
                </div>  
            </field>
        </record>

They could tell me how I can correct it.

Thank you.

**Comment by jjscarafia** [comment]
This module and the hole repository has been deprecated. Please check the
repository readme file
