### ISSUE TITLE
product_pack error when saving a quotation

### ISSUE THREAD

**Issue by colmeirin** [adhoc-dev/odoo-addons#4]
Hi there,

I've been messing around with your product_pack module in a Odoo 8 installation.
I can create packs as a product variant of a product and store it.

When I add this product to a sale quotation the following error appears:

OpenERP Server Error
Traceback (most recent call last):
  File "/Users/colmeirin/odoo/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/colmeirin/odoo/openerp/http.py", line 535, in dispatch
    result = self._call_function(*_self.params)
  File "/Users/colmeirin/odoo/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/Users/colmeirin/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/Users/colmeirin/odoo/openerp/http.py", line 291, in checked_call
    return self.endpoint(_a, *_kw)
  File "/Users/colmeirin/odoo/openerp/http.py", line 751, in __call__
    return self.method(_args, *_kw)
  File "/Users/colmeirin/odoo/openerp/http.py", line 387, in response_wrap
    response = f(_args, *_kw)
  File "/Users/colmeirin/odoo/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/colmeirin/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/Users/colmeirin/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/Users/colmeirin/odoo/other/test/odoo-addons/product_pack/sale.py", line 25, in create
    self.expand_packs(cr, uid, [result], context)
  File "/Users/colmeirin/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/Users/colmeirin/odoo/other/test/odoo-addons/product_pack/sale.py", line 158, in expand_packs
    'procurement_id': line.procurement_id and line.procurement_id.id or False,
AttributeError: 'sale.order.line' object has no attribute 'procurement_id'

**Comment by jjscarafia** [comment]
Product pack has been remade partially to introduce new functionality, old functionality not migrated yet. We are going to analize if we migrate it or not...
