### ISSUE TITLE
Trying to install, I get this error. Could you help?

### ISSUE THREAD

**Issue by lapagept** [adhoc-dev/odoo-addons#41]
2015-04-25 18:16:59,943 27075 INFO 03test openerp.models: storing computed values of fields.function 'product_uom'
2015-04-25 18:16:59,959 27075 ERROR 03test openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo-test/odoo-test/openerp/http.py", line 525, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 562, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 302, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 299, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 791, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo-test/odoo-test/openerp/http.py", line 395, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo-test/odoo-test/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo-test/odoo-test/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo-test/odoo-test/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo-test/odoo-test/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo-test/odoo-test/openerp/modules/loading.py", line 363, in load_modules
    loaded_modules, update_module)
  File "/home/odoo-test/odoo-test/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo-test/odoo-test/openerp/modules/loading.py", line 163, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/odoo-test/odoo-test/openerp/modules/module.py", line 296, in init_module_models
    t[1](cr, *t[2])
  File "/home/odoo-test/odoo-test/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-test/odoo-test/openerp/models.py", line 2243, in _update_store
    res = f.get(cr, self, iids, k, SUPERUSER_ID, {})
  File "/home/odoo-test/odoo-test/openerp/osv/fields.py", line 1361, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/odoo-test/odoo-test/openerp/osv/fields.py", line 1430, in _fnct_read
    value = value[field][:1]
  File "/home/odoo-test/odoo-test/openerp/models.py", line 5500, in __getitem__
    return self._fields[key].__get__(self, type(self))
KeyError: 'product_id'

**Comment by jjscarafia** [comment]
This should be solved now
